api:
  # URL for your Guardium appliance, including port. Default https port is 8443.
  guardium-api-url: "https://guard.gdemo.com:8443"

  # You must register a client prior to using any REST APIs
  # Full instructions for registering an oAuth client can be found here:
  # https://www.ibm.com/docs/en/gdp/12.x?topic=commands-using-guardium-rest-apis#using_rest_api__register_api__title__1
  # example: grdapi register_oauth_client client_id=client1 grant_types="password"

  oauth-client-id: "client1"
  oauth-client-secret: "81399384-6351-46fd-9cb3-ea7c2501cce3"

  # Guardium username with admin privileges. This, along with the OAuth client, will be used to get an access token
  guardium-admin-username: "admin"
  guardium-admin-password: "admin password here"

cli:
  # Guardium appliance CLI port - default is 22
  guardium-cli-hostname: "guard.gdemo.com"
  guardium-cli-port: "22"
  guardium-cli-username: "cli"
  guardium-cli-password: "cli password here"

  # Optional: SSH proxy for CLI
  # Use this if having to ssh through a proxy to reach the Guardium CLI/SSH
  ssh-proxy:
    enabled: "True"
    ssh-proxy-hostname: "proxy.example.com"
    ssh-proxy-port: "20755"
    ssh-proxy-username: "proxy username here"
    ssh-proxy-password: "proxy ssh password here"